# Generated by Django 5.2.7 on 2026-01-06 17:49

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('registration_number', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('tax_id', models.CharField(max_length=50)),
                ('classification', models.CharField(max_length=100)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('project_type', models.CharField(choices=[('civil', 'Civil Works'), ('electrical', 'Electrical Installation'), ('mechanical', 'Mechanical Works'), ('marine', 'Marine Works'), ('dredging', 'Dredging Works'), ('maintenance', 'Maintenance'), ('rehabilitation', 'Rehabilitation'), ('new_construction', 'New Construction')], max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('port_location', models.CharField(blank=True, max_length=100)),
                ('estimated_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('approved_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('spent_budget', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('proposed_start_date', models.DateField()),
                ('proposed_end_date', models.DateField()),
                ('approved_start_date', models.DateField(blank=True, null=True)),
                ('approved_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('critical', 'Critical Priority')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_projects', to=settings.AUTH_USER_MODEL)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.contractor')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_projects', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('report_date', models.DateField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('percentage_complete', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('work_accomplished', models.TextField()),
                ('challenges', models.TextField(blank=True)),
                ('next_activities', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='projects.project')),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('document_type', models.CharField(choices=[('proposal', 'Project Proposal'), ('feasibility_study', 'Feasibility Study'), ('tor', 'Terms of Reference'), ('boq', 'BOQ/BEME'), ('technical_spec', 'Technical Specifications'), ('tender_doc', 'Tender Document'), ('contract', 'Contract Agreement'), ('progress_report', 'Progress Report'), ('payment_cert', 'Payment Certificate'), ('completion_cert', 'Completion Certificate'), ('inspection_report', 'Inspection Report'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='project_documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('review_date', models.DateField()),
                ('findings', models.TextField()),
                ('recommendations', models.TextField()),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('approved_with_revisions', 'Approved with Revisions'), ('rejected', 'Rejected'), ('deferred', 'Deferred')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committee_members', models.ManyToManyField(related_name='technical_committees', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_reviews', to='projects.project')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stage_type', models.CharField(choices=[('site_inspection', 'Site Inspection'), ('project_proposal', 'Project Proposal Preparation'), ('feasibility_study', 'Feasibility Study'), ('due_diligence', 'Due Diligence (Terms of Reference)'), ('prepare_boq', 'Prepare BOQ/BEME'), ('technical_review', 'Technical Review Committee'), ('forward_gm', 'Forward to General Manager Engineering'), ('forward_ed', 'Forward to Executive Director Engineering'), ('tender_process', 'Tender Process'), ('contract_award', 'Contract Award'), ('nominate_pm', 'Nomination of Project Manager/Supervisor'), ('commencement', 'Commencement of Project'), ('supervision', 'Supervision (Monitoring & Evaluation)'), ('progress_report', 'Submission of Progress Report'), ('payment_certificate', 'Project Certification (Payment Certificate)'), ('completion', 'Project Completion/Commissioning'), ('retention_certificate', 'Certification of Retention'), ('final_report', 'Final Project Report')], max_length=50)),
                ('order', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked'), ('requires_approval', 'Requires Approval')], default='pending', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('contract_reference', models.CharField(blank=True, max_length=100)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='project_documents/stages/')),
                ('is_document_uploaded', models.BooleanField(default=False)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stages', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_stages', to=settings.AUTH_USER_MODEL)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.contractor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.project')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('project', 'stage_type')},
            },
        ),
    ]
