# Generated by Django 5.2.7 on 2026-01-09 16:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boq_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('section', models.CharField(default='Main', max_length=100)),
                ('subsection', models.CharField(blank=True, max_length=100)),
                ('item_number', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('unit', models.CharField(choices=[('item', 'Item'), ('nos', 'Nos'), ('sqm', 'Sqm'), ('m', 'M'), ('m2', 'M²'), ('m3', 'M³'), ('kg', 'Kg'), ('ton', 'Ton'), ('day', 'Day'), ('hour', 'Hour'), ('lot', 'Lot')], default='item', max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('project_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_items', to='projects.projectstage')),
            ],
            options={
                'ordering': ['section', 'subsection', 'order', 'item_number'],
            },
        ),
    ]
