# Generated by Django 5.2.7 on 2026-01-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_boqitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boqitem',
            options={'ordering': ['order', 'item_number']},
        ),
        migrations.RemoveField(
            model_name='boqitem',
            name='subsection',
        ),
        migrations.AlterField(
            model_name='boqitem',
            name='item_number',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='boqitem',
            name='section',
            field=models.CharField(default='Main Section', max_length=100),
        ),
    ]
