# Generated by Django 5.2.7 on 2026-02-14 17:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_projectstage_forward_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="contingencies",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="contract_award_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="contract_award_ref",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="contract_sum",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total contract sum",
                max_digits=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="contractor_address",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="project",
            name="contractor_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name="PaymentCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("certificate_no", models.CharField(max_length=50)),
                ("certificate_date", models.DateField()),
                (
                    "contingencies",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "estimated_omission",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "estimated_addition",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "work_completed_to_date",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "cost_of_escalation",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "materials_on_site",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "retention_rate",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
                ),
                (
                    "fluctuation_claims",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "refund_advance_payment",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "amount_previously_certified",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_certificates",
                        to="projects.project",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_certificates",
                        to="projects.projectstage",
                    ),
                ),
            ],
            options={
                "ordering": ["-certificate_date"],
            },
        ),
    ]
