# Generated by Django 5.2.7 on 2026-02-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_contingencies_project_contract_award_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="advance_payment",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="contract_completion_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="contract_duration",
            field=models.IntegerField(
                blank=True, help_text="Duration in days", null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="performance_bond",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="retention_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=5.0, max_digits=5, null=True
            ),
        ),
    ]
