# Generated by Django 5.2.7 on 2026-02-16 10:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_advance_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='port_location',
        ),
        migrations.AddField(
            model_name='project',
            name='budget_head',
            field=models.CharField(blank=True, help_text='Budget head code/reference', max_length=100),
        ),
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.CharField(choices=[('civil', 'Civil Engineering'), ('electrical', 'Electrical Engineering'), ('mechanical', 'Mechanical Engineering'), ('marine', 'Marine Engineering'), ('planning', 'Planning & Design'), ('maintenance', 'Maintenance'), ('dredging', 'Dredging'), ('csr', 'Corporate Social Responsibility')], default='civil', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='other_location',
            field=models.CharField(blank=True, help_text="Specify if location is 'Other'", max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(choices=[('hq', 'Headquarters (HQ)'), ('lpc', 'Lagos Port Complex (LPC)'), ('tincan', 'Tincan Island Port Complex (TCIPC)'), ('rivers', 'Rivers Port (RP)'), ('delta', 'Delta Port (DP)'), ('calabar', 'Calabar Port (CAL)'), ('lekki', 'Lekki Port'), ('flt', 'Federal Lighter Terminal Onne (FLT)'), ('fot', 'Federal Ocean Terminal (FOT)'), ('other', 'Other')], default='hq', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='proposed_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='proposed_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('department', models.CharField(choices=[('civil', 'Civil Engineering'), ('electrical', 'Electrical Engineering'), ('mechanical', 'Mechanical Engineering'), ('marine', 'Marine Engineering'), ('planning', 'Planning & Design'), ('maintenance', 'Maintenance'), ('dredging', 'Dredging'), ('csr', 'Corporate Social Responsibility')], max_length=50)),
                ('year', models.IntegerField()),
                ('budget_type', models.CharField(choices=[('capex', 'CAPEX - Capital Expenditure'), ('opex', 'OPEX - Operational Expenditure'), ('overhead', 'Overhead'), ('special', 'Special Project')], max_length=20)),
                ('ctr', models.CharField(help_text='Cost Tracking Reference', max_length=50)),
                ('expenditure_description', models.TextField()),
                ('proposed_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('justification', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('section', models.CharField(default='Main Budget', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='projects.project')),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
    ]
