# Generated by Django 5.2.7 on 2026-02-16 14:58

from django.db import migrations, models  # Add models here
import uuid  # Add uuid import


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_project_port_location_project_budget_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='item_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
