# Generated by Django 5.2.7 on 2026-02-18 14:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_fix_budget_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetitem',
            name='budget_id',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='budget_type',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='department',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='project',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='year',
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('budget_code', models.CharField(help_text='e.g., ENG-CAP-2026-001', max_length=50, unique=True)),
                ('budget_head', models.CharField(max_length=200)),
                ('department', models.CharField(choices=[('civil', 'Civil Engineering'), ('electrical', 'Electrical Engineering'), ('mechanical', 'Mechanical Engineering'), ('marine', 'Marine Engineering'), ('planning', 'Planning & Design'), ('maintenance', 'Maintenance'), ('dredging', 'Dredging'), ('csr', 'Corporate Social Responsibility')], max_length=50)),
                ('year', models.IntegerField()),
                ('budget_type', models.CharField(choices=[('capex', 'CAPEX - Capital Expenditure'), ('opex', 'OPEX - Operational Expenditure'), ('overhead', 'Overhead'), ('special', 'Special Project')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'department', 'budget_code'],
            },
        ),
        migrations.AddField(
            model_name='budgetitem',
            name='budget',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.budget'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_allocations', to='projects.budget')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'budget')},
            },
        ),
        migrations.CreateModel(
            name='ProjectNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomination_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nomination_type', models.CharField(choices=[('project_manager', 'Project Manager'), ('supervisor', 'Project Supervisor')], max_length=20)),
                ('nominee_location', models.CharField(max_length=100)),
                ('project_location', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending_gm', 'Pending GM Approval'), ('pending_ed', 'Pending ED Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_gm', max_length=20)),
                ('gm_approved_at', models.DateTimeField(blank=True, null=True)),
                ('ed_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('ed_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ed_approved_nominations', to=settings.AUTH_USER_MODEL)),
                ('gm_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gm_approved_nominations', to=settings.AUTH_USER_MODEL)),
                ('nominated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominated_projects', to=settings.AUTH_USER_MODEL)),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_nominations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'nomination_type', 'nominee')},
            },
        ),
    ]
