# Generated by Django 5.2.7 on 2026-02-18 15:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_budgetitem_budget_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectnomination',
            unique_together={('project', 'nomination_type', 'nominee', 'status')},
        ),
        migrations.AddField(
            model_name='projectnomination',
            name='nominator_office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectnomination',
            name='nominee_department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectnomination',
            name='nominee_office',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='projectnomination',
            name='nominee_location',
        ),
    ]
