# Generated by Django 5.2.7 on 2026-01-06 17:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('office', models.CharField(choices=[('executive_director', 'Executive Director'), ('general_manager', 'General Manager'), ('assistant_general_manager', 'Assistant General Manager'), ('chief_port_engineer', 'Chief Port Engineer'), ('unit_head', 'Unit Head'), ('engineer', 'Engineer')], default='engineer', max_length=50)),
                ('grade_level', models.IntegerField(blank=True, choices=[(16, 'GL 16 - Director'), (15, 'GL 15 - Deputy Director'), (14, 'GL 14 - Assistant Director'), (13, 'GL 13 - Chief Engineer'), (12, 'GL 12 - Principal Engineer'), (10, 'GL 10 - Senior Engineer'), (9, 'GL 9 - Engineer I'), (8, 'GL 8 - Engineer II')], null=True)),
                ('department', models.CharField(choices=[('civil', 'Civil Engineering'), ('electrical', 'Electrical Engineering'), ('mechanical', 'Mechanical Engineering'), ('marine', 'Marine Engineering'), ('planning', 'Planning & Design'), ('maintenance', 'Maintenance'), ('dredging', 'Dredging'), ('environmental', 'Environmental Engineering')], max_length=50)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('signature_pin', models.CharField(blank=True, max_length=6, null=True)),
                ('pin_set', models.BooleanField(default=False)),
                ('is_approving_officer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-grade_level', 'last_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
