# Generated by Django 5.2.7 on 2026-02-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('civil', 'Civil Engineering'), ('electrical', 'Electrical Engineering'), ('marine', 'Marine Engineering'), ('planning', 'Planning & Design'), ('maintenance', 'Maintenance'), ('dredging', 'Dredging')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade_level',
            field=models.IntegerField(blank=True, choices=[(16, 'GL 17 - Executive Director'), (16, 'GL 16 - General Manager'), (15, 'GL 15 - Asst. General Manager'), (14, 'GL 14 - Principal Manager'), (13, 'GL 13 - Senior Manager'), (12, 'GL 12 - Manager'), (10, 'GL 10 - Asst. Manager'), (9, 'GL 9 -  I'), (8, 'GL 8 -  II')], null=True),
        ),
    ]
